name: pass_data_preparation
channels:
  - conda-forge
  - plotly

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - pandas
  - pip
  - pytask>=0.0.14
  - pytask-latex>=0.0.12


  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz


  - virtualenv=20.0.33

  - pip:

    - pre-commit

    - kaleido
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - sphinxcontrib.bibtex

